version: '3.7'

services:
  rabbitmq:
    env_file:
      - ./.env
    user: "${RUID}:${RGID}"
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    restart: unless-stopped
    environment:
        RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
        RABBITMQ_DEFAULT_USER: "rabbitmq"
        RABBITMQ_DEFAULT_PASS: "rabbitmq"
        RABBITMQ_DEFAULT_VHOST: "/"
    ports:
        - "5672:5672"
        - "15672:15672"
    labels:
        NAME: "rabbitmq"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # чтобы подкл менеджер по 15672  см   https://github.com/docker-library/rabbitmq/issues/260
      - ./rabbit_enabled_plugins:/etc/rabbitmq/enabled_plugins
      - ./rabbitmq-files/conf/:/etc/rabbitmq/
      - ./rabbitmq-files/data/:/var/lib/rabbitmq/
      - ./rabbitmq-files/log/:/var/log/rabbitmq/
    networks:
      rabbitmq_net:
        ipv4_address: "${INNER_IP}"
networks:
  rabbitmq_net:
    name: rabbitmq_net
    driver: bridge
    ipam:
      config:
        - subnet: "${INNER_SUBNET_IP}/16"
        - gateway: "${INNER_GATEWAY_IP}"
    internal: true
