version: '3.7'

services:
  rabbitmq:
    env_file:
      - ./.env
    user: "${RUID}:${RGID}"
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    restart: unless-stopped
    environment:
        RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
        RABBITMQ_DEFAULT_USER: "rabbitmq"
        RABBITMQ_DEFAULT_PASS: "rabbitmq"
        RABBITMQ_DEFAULT_VHOST: "/"
    ports:
        - "15672:15672"
        - "5672:5672"
    labels:
        NAME: "rabbitmq"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./rabbitmq-files/conf/:/etc/rabbitmq/
      - ./rabbitmq-files/data/:/var/lib/rabbitmq/
      - ./rabbitmq-files/log/:/var/log/rabbitmq/
    networks:
      - rabbitmq_net

networks:
  rabbitmq_net:
    name: rabbitmq_net
    driver: bridge
    internal: true
